name: autiscope_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  #data
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  dio: ^5.3.2
  flutter_secure_storage: ^9.0.0
  cloud_firestore: ^4.15.6
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  #domain
  equatable: ^2.0.5
  dartz: ^0.10.1
  #presentation
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  otp_pin_field: ^1.2.2
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.6
  video_player: ^2.8.2
  chewie: ^1.7.5
  intl: ^0.18.1
  camera: ^0.10.5+9
  image: ^3.2.2
  path_provider: ^2.1.2
  mailer: ^6.1.0
  flutter_localizations:
    sdk: flutter
  permission_handler: ^11.3.0
  just_audio: ^0.9.36
  tflite_audio: ^0.3.0
  flutter_flip_card: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
    - video/
    - audios/
    - models/